### ISSUE TITLE
Rough Roadmap

### ISSUE THREAD

**Issue by burrrata** [burrrata/hack.aragon4all#20]
## ASAP: skeleton with placeholder content to prove the idea is solid
- [x] opaque text background on text for the mainpage (not as ideal as opaque text boxes that "pop", but it's good enough for now)
- [x]  update the sync-script and sidebar to pull in the `README.md` for each app's docs vs an `overview.md` doc 
- [x]  update all the Temp TPS Docs to conform to the new docs standard (pictures, chat links, etc...)
- [x] fill in temp-tps-docs with info from [TPS GitHub](https://github.com/AutarkLabs/planning-suite) and the [Medium posts](https://medium.com/@stellarmagnet/that-planning-suite-live-on-rinkeby-c2332e2e5e27). (this will take a min)
- [x] add LICENSE.md
- [x] update blog with something Autark related vs the filler content
- [x]  update the "Who is Using This?" section of the mainpage with placeholder content'
- [x] fill in CONTRIBUTING section with open positions and some basic info
- [x] update homepage links to point to the DEVELOPERS docs vs the current Autark GitHub

The goal here is to work on the architecture: what goes where. Once we have the general framework in place, we can work on optimizing the content and getting feedback from the community. 

This is important because it makes the ideas come alive so that you can see what might actually work in practice vs just a nice theory. It also creates something concrete to anchor conversations around.

<br>

## The Real Work: once the CFDAO Grant goes through
- [ ] talk to Autark team to refine the docs into something that addresses their pain points and dev ux goals
- [ ] update DEVELOPER section sidebar to look cool with titles and nested sub menus like hack.aragon does - our [`sidebars.js`](https://github.com/aragon/hack/blob/master/website/sidebars.json) files have the same structure, so it must be handled by custom [css](https://github.com/aragon/hack/blob/master/website/static/css/custom.css)
- [ ] update DEVELOPER section with a custom css for fonts and UI
- [ ] brainstorm with Autark team to understand their desires and pain points around docs => update "doc standards" templates and TPS examples accordingly
- [ ] make the TPS apps section more interactive => UI with picture and name for each, then click to be taken to the dev experience for that app
- [ ] get feedback on mainpage filler content and update it with stuff that Autark actually wants
- [ ] change the license to what hack.aragon uses https://github.com/aragon/hack/blob/master/LICENSE
- [ ] fix all the things in the [UI Distractions](https://github.com/burrrata/hack.aragon4all/issues/17) Issue

<br>

## Minimal Viable Prototype: demo for the Nest Grant
- [ ] share with broader Aragon community to get feedback
- [ ] share with A1, Black, and 1Hive to get feedback as to if they would want something like this and/or what features and adjustments they'd like to see
- [ ] explore what "developer support", tutorials, and bounties would look like as a standard feature, first for Autark and then also for the broader Aragon ecosystem

**Comment by burrrata** [comment]
CANCELLED because the CFDAO process is way too clunky and time consuming to be worth the effort.
